### ISSUE TITLE
Les obstacles

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/nuit-info-2019-TEAM-SOCKET#4]
## TODO

- [x] spawn aléatoire (haut ou bas)

- [x] Ils défilent le long de l'écran ( de droite a gauche)

- [x] Ils disparaissent quand ils dépassent la bordure du canvas

- [x] Accélération du défilement en fonction du temps ( a un max)
